Repository AY2425S2-CS2103-F15-3/tp, pull requests merged in 2025-04, with the labels that each got.

#152 Add UML activity diagrams for remove-tags and edit-tag
  docs/DeveloperGuide.md
  docs/diagrams/EditTagActivityDiagram.puml
  docs/diagrams/RemoveTagsActivityDiagram.puml
  src/main/java/seedu/recruittrackpro/logic/Messages.java
Labels: type.Task

#176 Unclear Error Message When Finding by Tag with Blank or Whitespace Input
  src/main/java/seedu/recruittrackpro/model/tag/Tag.java
Labels: alpha-bug

#183 Edit-tag result message "from" tag uses user input instead of matched tag #170
  src/main/java/seedu/recruittrackpro/logic/commands/EditTagCommand.java
Labels: alpha-bug

#186 Sort button styling not cohesive
  src/main/resources/view/DarkTheme.css
Labels: alpha-bug

#188 Sort button label not intuitive
  src/main/java/seedu/recruittrackpro/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#191 Edit-tag on a filtered list should not show full list after execution
  src/main/java/seedu/recruittrackpro/logic/commands/EditTagCommand.java
Labels: alpha-bug

#173 Find --contain-all option
  src/main/java/seedu/recruittrackpro/logic/commands/FindCommand.java
  src/main/java/seedu/recruittrackpro/logic/parser/FindCommandParser.java
  src/main/java/seedu/recruittrackpro/logic/predicates/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/recruittrackpro/logic/predicates/ContainsKeywordsPredicate.java
  src/main/java/seedu/recruittrackpro/logic/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/recruittrackpro/logic/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/recruittrackpro/logic/predicates/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/recruittrackpro/logic/predicates/TagContainsKeywordsPredicate.java
  src/test/java/seedu/recruittrackpro/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recruittrackpro/logic/commands/FindCommandTest.java
  src/test/java/seedu/recruittrackpro/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/recruittrackpro/logic/parser/RecruitTrackProParserTest.java
  src/test/java/seedu/recruittrackpro/logic/predicates/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/recruittrackpro/logic/predicates/ContainsKeywordsPredicateTest.java
  src/test/java/seedu/recruittrackpro/logic/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/recruittrackpro/logic/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/recruittrackpro/logic/predicates/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/recruittrackpro/logic/predicates/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/recruittrackpro/model/ModelManagerTest.java
Labels: type.Task

#190 Remove-tags on a filtered list should not show full list after execution
  src/main/java/seedu/recruittrackpro/logic/commands/RemoveTagsCommand.java
  src/test/java/seedu/recruittrackpro/logic/commands/RemoveTagsCommandTest.java
Labels: alpha-bug

#198 Tags string is incorrectly formatted in person description of result message
  src/main/java/seedu/recruittrackpro/logic/Messages.java
Labels: alpha-bug

#211 Help menu bar should refer to User Guide
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#215 Add --contain-all to DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#193 Unclear Error Message When Finding by Comment with Blank or Whitespace Input
  src/main/java/seedu/recruittrackpro/logic/parser/FindCommandParser.java
Labels: alpha-bug

#209 Displayed messages should not include comments and tags if they are empty
  src/main/java/seedu/recruittrackpro/logic/Messages.java
  src/test/java/seedu/recruittrackpro/logic/commands/EditCommandTest.java
Labels: alpha-bug

#218 Add add-tags to UG
  docs/UserGuide.md
Labels: type.Task

#235 Add remove-tags and edit-tag into User Guide
  docs/UserGuide.md
Labels: type.Task

#237 Reverse the icon for toggle theme
  src/main/java/seedu/recruittrackpro/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#290 [PE-D][Tester B] DG: Activity diagram under "Find by tag feature" has error
  docs/diagrams/FindActivityDiagram.puml
Labels: type.DocumentationBug

#288 [PE-D][Tester A] Documentation missing/misleading for -ca option in find command
  docs/UserGuide.md
Labels: type.DocumentationBug

#291 [PE-D][Tester B] DG: Switch sort feature activity diagram branch missing guard
  docs/diagrams/SwitchSortActivityDiagram.puml
Labels: type.DocumentationBug

#289 [PE-D][Tester B] Sort by alphabet is really sort by string comparison, which is bad as a user experience.
  docs/UserGuide.md
  docs/images/SwitchSortExample.png
Labels: type.DocumentationBug
